#!/bin/bash

# make sure docker is available to use
command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }

docker run -i -v "$HOME/:/context" -e SLACKME_FILE=/context/.slackme pjvds/slackme "$@"
